spring:
  datasource:
    username: root
    password: cooper2021
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/post_db
  jpa:
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: none
  flyway:
    user: root
    password: cooper2021
    enabled: true
    baseline-on-migrate: false
    locations: classpath:/db/migration
